from . import account_move
from . import account_payment
from . import mechanic_brand
from . import mechanic_vehicle_maintenance
from . import helpdesk_ticket
from . import mechanic_vehicle
from . import mechanic_workorder
from . import product_template
from . import res_config_settings
from . import sale_order